
Training tokens classifier
Traceback (most recent call last):
  File "/Users/filip/thesis/Classifier.py", line 264, in <module>
    fire.Fire(handler)
  File "/Users/filip/opt/anaconda3/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/Users/filip/opt/anaconda3/lib/python3.9/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/Users/filip/opt/anaconda3/lib/python3.9/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/Users/filip/thesis/Classifier.py", line 259, in handler
    testTokensClassifier()
  File "/Users/filip/thesis/Classifier.py", line 230, in testTokensClassifier
    loss = criterion(outputs, labels)
  File "/Users/filip/opt/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/filip/opt/anaconda3/lib/python3.9/site-packages/torch/nn/modules/loss.py", line 1150, in forward
    return F.cross_entropy(input, target, weight=self.weight,
  File "/Users/filip/opt/anaconda3/lib/python3.9/site-packages/torch/nn/functional.py", line 2846, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
ValueError: Expected input batch_size (32) to match target batch_size (1).